apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8auto-test-1
  namespace: default
spec:
  secretName: k8auto-test-1-tls
  dnsNames:
    - k8auto.certforge.xyz
  issuerRef:
    name: certforge
    kind: CertForgeClusterIssuer
    group: certforge.io
